sudo: false
language: php
php:
  - 5.6

services:
  - mysql

cache:
    directories:
        - $HOME/download-cache

addons:
  hosts:
    - dev.casebox.local

before_install:
    - mkdir -p $HOME/download-cache
    - mkdir -p build/logs
    - mkdir -p logs
    - mkdir -p data/tmp/minify
    - mysql -u root -e "CREATE USER 'test'@'%' IDENTIFIED BY 't3st'"
    - mysql -u root -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 't3st'"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'test'@'%'"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'test'@'localhost'"

install:
#   - pecl install mbstring
#   - pecl install curl
   - curl -sS https://getcomposer.org/installer | php
#   - php composer.phar install --no-interaction
   - php composer.phar install --no-interaction
#   - echo "See php extensions:"
#   - php -m


before_script:
  # copy and install solr
   - export SOLR_VERSION="5.2.0"
   - export SOLR_PORT="8983"
   - bash tests/server/solr/solr5-install.sh
   # may take few seconds to start and may not be available when the script is executed
   - sleep 3
  # add solr core cbtest_log
   - export SOLR_CORENAME="cbtest_log"
   - export SOLR_CONFIGSET="cbtest_log"
   - bash tests/server/solr/solr5-addcore.sh
  # add solr core test
   - export SOLR_CORENAME="cbtest_test"
   - export SOLR_CONFIGSET="cbtest_default"
   - bash tests/server/solr/solr5-addcore.sh
  # add php extensions
#   - phpenv config-add "${TRAVIS_BUILD_DIR}/tests/server/php/config-extensions.ini"
  # autoinstall CASEBOX
   - php tests/auto_install.php

script:
   - vendor/bin/phpunit -c tests/phpunit-travis.xml 

after_script:
 - if [ -f vendor/bin/coveralls ] ; then php vendor/bin/coveralls -v || true ; fi
 - bash tests/server/solr/solr5-stop.sh
